### ISSUE TITLE
Is there a way to customize the Thumbnails?

### ISSUE THREAD

**Issue by a-tonchev** [yifaneye/react-gallery-carousel#11]
I would like to use bigger thumbnails, is there a way to customize the thumbnails?

**Comment by yifaneye** [comment]
Hi @a-tonchev ! Thank you for raising this issue up! 😄

There is currently no way to customize the thumbnails. I will make the thumbnails' size customization available and publish a new version before the end of next week. 👨🏻‍💻 Rest assured that there will be no breaking changes. I will notify you for the new version.

**Comment by a-tonchev** [comment]
Hi @yifaneye thanks,

i think the best would be to be able to wrap the thumbnails in a custom element. E.g.

**Comment by yifaneye** [comment]
@a-tonchev Thank you for your advice! I will see what customisation I can do with it!
