### ISSUE TITLE
Smooth transition when chosing thumbnail

### ISSUE THREAD

**Issue by a-tonchev** [yifaneye/react-gallery-carousel#13]
I love the way the thumbnails are scrolled, but when I click on some of them the transition is not that smooth. 

Probably it would be possible to make some transition like this one:

https://www.linxtion.com/demo/react-image-gallery/

They thumbnails move more natural on transition.

I will see if I have time I could try to do some pull requests. ;)

**Comment by yifaneye** [comment]
Hi @a-tonchev ! Thank you for raising this issue up! 😄

Thank you for your love on "the way the thumbnails are scrolled"! The thumbnails are not scrollable in the link that you provided, but have a nice transition.
![SS 2021-04-20 at 16 15 22](https://user-images.githubusercontent.com/49315663/115346586-b0301c80-a1f3-11eb-865b-0d0c3beba42a.jpg)

To make the transition available, you can edit https://github.com/yifaneye/react-gallery-carousel/blob/master/src/utils/useAnchor.js#L13. Please also don't forget to skip the transition for people with reduced motion turned on. I look forward to review your pull request! 😉

**Comment by yifaneye** [comment]
Hi @a-tonchev , 

I enabled smooth transition!
![May-02-2021 16-34-03](https://user-images.githubusercontent.com/49315663/116804755-bc599980-ab64-11eb-9c37-107d7fece788.gif)

Currently, smooth transition does not support Safari and IE.

**Comment by a-tonchev** [comment]
@yifaneye Somehow I don't see this change, are you sure that it is merged?

**Comment by yifaneye** [comment]
@a-tonchev , yes, I am sure. It is on by default. However, I am not sure if you know this already, but I said "currently, smooth transition does not support Safari and IE."
