### ISSUE TITLE
The last slide is not displayed from the second loop when there are exactly 2 slides

### ISSUE THREAD

**Issue by yifaneye** [yifaneye/react-gallery-carousel#2]
**Describe the bug**
The last slide is not displayed from the second loop in carousel with loop when there are exactly 2 slides.

**To Reproduce**
1. Make a carousel with loop and with 2 slides
2. Click on the right arrow button to loop all slides once 
3. Click on the right arrow button to go to the last slide
4. See the error that the last slide is not displayed

**Expected behavior**
The last image should be display at the last index.

**Screenshots**
The GIF below is taken from the initial loading to the occurrence of the bug.
![second_image_issue](https://user-images.githubusercontent.com/49315663/114260618-6ee08580-9a19-11eb-9dbd-ceb34dd1f6ee.gif)

**Desktop (please complete the following information):**
 - macOS
 - Chrome
 - Version 89.0.4389.90 (Official Build) (x86_64)

**Comment by Lewis-Seekio** [comment]
又是我！😂 I also have this problem!

**Comment by yifaneye** [comment]
I am sorry to hear that! Please rest assured that I have fixed it on my machine. I will release an update today. 😉

**Comment by yifaneye** [comment]
This issue is now fixed in v0.1.2

**Comment by yifaneye** [comment]
Here is the carousel to show that the bug is fixed.
The GIF below is taken from the initial loading to the place where the bug had occurred.
![carousel_issue_fixed](https://user-images.githubusercontent.com/49315663/114327039-c4807380-9b7a-11eb-90c3-f2bd38644430.gif)
