### ISSUE TITLE
Caption for image always has vertical and horizontal scrolls even they are not required

### ISSUE THREAD

**Issue by sergru** [yifaneye/react-gallery-carousel#26]
**To Reproduce**
Use react-gallery-carousel with "images" and "hasCaptions" attributes. All caption elements have vertical and horizontal scrollbars even if the caption element doesn't require them.

**Expected behavior**
No scrollbars if they are not required.

**To Fix**
Replace "overflow: scroll" to "overflow: auto" caption's css style letting browser to handle scrollbars appearance.

**Comment by yifaneye** [comment]
Hi @sergru ! Thank you for raising this issue up! 😄

I normally set the "Show scroll bars:" setting to "Automatically based on mouse or trackpad" and I always use trackpad. 😅
![SS 2021-05-03 at 19 11 11](https://user-images.githubusercontent.com/49315663/116859842-fcdc1480-ac43-11eb-9275-d957cc64b5d6.jpg)

I replicate this issue after turning the "Show scroll bars:" setting to "Always". 😅
![SS 2021-05-03 at 19 11 19](https://user-images.githubusercontent.com/49315663/116859850-ffd70500-ac43-11eb-87fe-71ffb0f66d0c.jpg)

I successfully fixed this issue in the dev tool using the method that you provided! I thank you for advising me the method to fix it. 😀
![SS 2021-05-03 at 19 12 58](https://user-images.githubusercontent.com/49315663/116859861-02d1f580-ac44-11eb-8271-854fd0314e1d.jpg)

I will fix this issue and publish a new patch version before the end of this week. 👨🏻‍💻 Rest assured that there will be no breaking changes.
