### ISSUE TITLE
TypeError: Cannot read property 'style' of null randomly appears

### ISSUE THREAD

**Issue by Lewis-Seekio** [yifaneye/react-gallery-carousel#3]
**Describe the bug**
Random bug when component loads, only happens sometimes. Happens randomly!

**Screenshots**
![image](https://user-images.githubusercontent.com/80532100/114314164-75423080-9af1-11eb-962d-8a2b831862c4.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]

**Additional context**

**Comment by yifaneye** [comment]
Hi @Lewis-Seekio ! Thank you for bringing this issue up! 😄

I tried on my Edge browser on macOS. However, I can not replicate the issue you are having. Anyways, I will make some changes by doing a check before accessing the object's property.

I will make the improvement and publish a new version today.  I will notify you for the new version.

**Comment by yifaneye** [comment]
Hi @Lewis-Seekio! Actually, the bug will not have existed starting with v0.1.2. 😀 The v0.1.2 was published about 10 hours ago. Please install the latest version. I am sorry for the inconvenience. I should have make things robuster from the very start. 😅
