### ISSUE TITLE
TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by Lewis-Seekio** [yifaneye/react-gallery-carousel#31]
**Describe the bug**
The error line:

() => (slidesRef.current.style.transitionDuration = null),

**To Reproduce**
1. Click on the page using the carousel
2. Click the browser back button to go back
3. Click forward to go back, the error will occur

**Screenshots**
https://gyazo.com/137e2ae73497db26a678f0dd0fffab61

**Desktop (please complete the following information):**
 - OS: Windwos
 - Browser Microsoft Edge

多谢！

**Comment by yifaneye** [comment]
Hi @Lewis-Seekio ! Thank you for bringing this issue up! 😄

I will try to replicate this issue locally. 😉

**Comment by yifaneye** [comment]
Hi @Lewis-Seekio ! I can not replicate this issue after trying a few times. Would you mind recording a video for me please! Thank you a lot in advance! 😃

**Comment by yifaneye** [comment]
Hi @Lewis-Seekio, I enhanced the robustness of the code. This will be included from the next patch version.
