### ISSUE TITLE
How to access the index of a slide ?

### ISSUE THREAD

**Issue by AnmolChhabra98** [yifaneye/react-gallery-carousel#35]
I want to know that how can I access the index of a slide so that I can change my text accordingly.

Thanks,

**Comment by yifaneye** [comment]
Hi @AnmolChhabra98 ! Thank you for bringing this issue up! 😄

If you mean the index of every slide, you can put your slides in an array and then use `slides.map((slide, index) => {});`. 😉

If you mean the index of the current slide, you can pass a callback function to `onIndexChange`. Please see https://github.com/yifaneye/react-gallery-carousel/blob/3adffccaf131e69eb084736aa24a0a2b47268fa8/src/components/Carousel/Carousel.js#L67 for more details. In fact I need to update the documentation to include the arguments. 😅

**Comment by AnmolChhabra98** [comment]
@yifaneye Thanks for your response . Yes , please update the documentation as it will be easy to understand then understanding from the code itself.

I tried onIndexChange argument but the problem with this is if you have hasDotButtons and you click on the same index or dot button of an image which identifies the same index . onIndexChange will trigger for this case also but it should not I guess because you are on the same index.

**Comment by AnmolChhabra98** [comment]
Steps to reproduce : 
1) Use hasDotButtons in your component.
2) Click on the present dot button.
3) Your onIndexChange will trigger instead of change in the Index.

**Comment by yifaneye** [comment]
Hi, @AnmolChhabra98 !

I think I get what you mean. The `onIndexChange` prop currently is called regardless of whether index value's before and after are the same. I will see what I am able to improve it this week.

**Comment by AnmolChhabra98** [comment]
Thanks @yifaneye It would be great . 

Can you please also tell me . Is it possible to use text , photos , videos in a single component 
eg:  Text slide then some photos  slide and then a video slide ?

**Comment by AnmolChhabra98** [comment]
Thanks @yifaneye for this info and for your wonderful package . 

Can you please guide me how can I toggle between object-fit value on minimized and maximized slide ? I am using user managed slides now the way you told me in above comment . I have tried toggleIsMaximized() . I am using this carousel component in one of my functional component. It would be a great help if I am able to do this .

**Comment by yifaneye** [comment]
Hi @AnmolChhabra98 !

Thank you for your appreciation! You can define an `isMaximized` state and pass it down to both the carousel component and your `img` element. When you pass to your `img` element, you can have a different `object-fit` value as `style` based on the `isMaximized` state (or `isMaximized` prop depending on whether you break down your components). Hope this helps!

**Comment by AnmolChhabra98** [comment]
Ok , Thank you @yifaneye . Will try to do this.

**Comment by yifaneye** [comment]
No worries @AnmolChhabra98
