### ISSUE TITLE
Add SSR support

### ISSUE THREAD

**Issue by docomoz** [yifaneye/react-gallery-carousel#36]
Please consider adding support for server-side rendering (SSR).

Here's what I got using your perfect (it is!) carousel with Gatsby:

```
"document" is not available during server side rendering.

See our docs page for more info on this error: https://gatsby.dev/debug-html

  2686 | var GalleryCarousel = function GalleryCarousel(props, ref) {
> 2687 |   var documentRef = useRef(document);
       |                           ^
  2688 |   var maximizedBackgroundRef = useRef(null);
  2689 |   var carouselRef = useRef(null);
  2690 |   var slidesContainerRef = useRef(null);


  WebpackError: ReferenceError: document is not defined

  - index.modern.js:2687
    [sns-front]/[react-gallery-carousel]/dist/index.modern.js:2687:27
```

**Comment by yifaneye** [comment]
Hi @docomoz ! Thank you for bringing this issue up! 😄

Thank you very much for your appreciation! I have not added SSR support for a component before. I will try my best to add SSR support. 😀 

Please advise me on any useful resource about adding SSR support to a component! 😃 Cheers!

**Comment by yifaneye** [comment]
Hi @docomoz ! I replicated this issue when using ```gatsby build```. 👌

**Comment by docomoz** [comment]
https://www.gatsbyjs.com/docs/debugging-html-builds/
See the first point.

It's easy. You should add conditions `if(typeof document !== "undefined")` or `if(typeof window !== "undefined")` every time you call window or document.

**Comment by yifaneye** [comment]
Hi @docomoz ! Thank you for the resource! I have started on the modification for SSR support today.

**Comment by kovart** [comment]
If you are using Next.js framework then we can import the library as follows:
```js
const Carousel = dynamic(() => import('react-gallery-carousel'), {
  ssr: false
});
```
The library will be imported only on the client-side. Official docs: [Dynamic import with no SSR](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr)

Also, there is an error with placeholder image:

> "Module parse failed: Unexpected character '�' "

We can fix it with "next-images" module in `next.config.js`:
```js
const withImages = require('next-images');

module.exports = withImages({ 
   webpack: (config) => {} // your config
})
```

Hope it helps you! 🙏

**Comment by csmaller** [comment]
just got the same issue with Gatsby build. hope you get it fixed soon, great widget.  you can also add a useEffect and check if document is there, then load idocument.

**Comment by yifaneye** [comment]
Hi @csmaller ! I will release the SSR support soon! Thank you for your advice!

**Comment by yifaneye** [comment]
Hi everyone! Thank you for the workarounds and tips! Thank you for your support! ❤️ 

I was a little busy for the last many weeks. Today, I finally finished adding SSR support. I am going to release a new version (v0.2.3) on the weekend!

**Comment by MaxiSantos** [comment]
> ```js
> require('next-images');
> ```

How did you imported next-image? I can't do it
With import I get: Cannot use import statement outside a module
And with requeire I get: Error: Cannot find module 'next-images'

**Comment by yifaneye** [comment]
Hi @MaxiSantos , I am not really familiar with Next.js. But I think the errors are generic and not specific to this library. @kovart Do you have any thoughts on this?

**Comment by MaxiSantos** [comment]
yes I did.. I think it was an issue related with module type.. anyway I'm not using next-image anymore since it brought other css style problems
