### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ShardanaSoft** [yifaneye/react-gallery-carousel#39]
Hi, 
first of all thanks for this amazing library.
are you planning to add types?

I'm using react with typescript.
For anyone in same situation, just put `//@ts-ignore` above the import.

**Comment by ShardanaSoft** [comment]
I'm sorry, I saw this is in your Roadmap. I'll close it. thanks again for your work.

**Comment by yifaneye** [comment]
Hi @ShardanaSoft ! Thank you for bringing this issue up! 😄

Thank you very much for your appreciation! I will add a type declaration before the end of next week. You do not need to be sorry! 😆

**Comment by ShardanaSoft** [comment]
Nice!! 💪 💪 I'll wait for it!

**Comment by guilhermefront** [comment]
@ShardanaSoft @yifaneye 

Types are available now. `npm install @types/react-gallery-carousel` to add it.

https://www.npmjs.com/package/@types/react-gallery-carousel

**Comment by yifaneye** [comment]
Hi @guilhermefront , thank you so much for adding the interface! I had a try. It worked perfectly! I will update the docs to include the typescript support!

**Comment by ShardanaSoft** [comment]
@guilhermefront works just fine. thanks for the update
