### ISSUE TITLE
Custom childrens for the thumbnails

### ISSUE THREAD

**Issue by a-tonchev** [yifaneye/react-gallery-carousel#40]
When we use "images" parameter, the thumbnails works great, but when we use children instead, thumbnail is exact the same like the main item.

It would be awesome to add thumbnailsChildren, where we can place separate thumbnails into the gallery.

e.g.

<Carousel
  thumbnails={thumbnails.map(thumbnail => <MyThumbnail src={thumbnail.src} />)}
>
   {images.map(image => <MyImage src={image.src} {...image.renderSomething} />)}
</Carousel>

**Comment by yifaneye** [comment]
Hi @a-tonchev ! Thank you for raising this issue up!

I will try to include this feature in the next version.

**Comment by KMouratidis** [comment]
Since the slides passed to `Thumbnails` are the same elements the user passes as children would something like this work?

```
// Carousel.js
const [slides, slidesElements] = useSlides(rawSlides, ...);
const thumbnailElements = props.thumbnails || slidesElements;

...

  const thumbnails = settings.hasThumbnails && (
    <Thumbnails
      slides={slidesElements}
      thumbnails={thumbnailElements}


// Thumbnails.js
<Thumbnail
    ...
    slide={props.slides[key]}
    thumbnail={props.thumbnails[key]}


// Thumnail.js:20
<UserSlideThumbnail slide={props.thumbnail} />
```

It seems to work for me when using it like below, but I'm not sure if it would break other parts of the code :confused: 

```
images = files.map(file => <img src={file} />)

      <Carousel ...props thumbnails={images}>
          {images}
      </Carousel>
```

**Comment by yifaneye** [comment]
Thanks @KMouratidis for your work! Would you like to open a pull request? I am happy to review and discuss it. 😃

**Comment by yifaneye** [comment]
Thanks for your contribution! Custom children for the thumbnails are now featured in v0.2.5. 😄
