### ISSUE TITLE
Not working on IOS/Safari

### ISSUE THREAD

**Issue by a-tonchev** [yifaneye/react-gallery-carousel#41]
The gallery is not working under IPhone/Safari, it shows following error message:

mediaQueryList.addEventListener is not a function. (In 'mediaQueryList.addEventListener('change', callback)', 'mediaQueryList.addEventListener' is undefined)

Apparently the window.matchMedia(query) does not have addEventListener/removeEventListener on some browsers.

This is called in one useSellect in react-gallery-carousel:

![image](https://user-images.githubusercontent.com/54528540/122241758-79147980-cecb-11eb-9078-9198b3357ec2.png)

If you don't have IOS, I can recommend you to try https://www.browserstack.com/, you can test there a little bit for free, or you can use some other IOS emulator

**Comment by a-tonchev** [comment]
I made a pull request which fix this issue, but you can feel free to make your own if you have an better idea :) 

https://github.com/yifaneye/react-gallery-carousel/pull/42

**Comment by yifaneye** [comment]
Hi @a-tonchev ! Thank you for raising this issue up!

Thank you for taking the time to make the pull request! I will review it tonight!

**Comment by yifaneye** [comment]
Hi @a-tonchev ! This issue is now fixed in v0.2.3!
