### ISSUE TITLE
Allow zoom in in mobile double tab

### ISSUE THREAD

**Issue by a-tonchev** [yifaneye/react-gallery-carousel#44]
Right now if I double tap image in full screen mode it has zoom in effect, but it zooms also arrows and the whole window. After exiting zoom I can not slide any more until I click again on the arrow, after that everything starts to work normal.

It would be nice to have double-tap and 2 finger stretch zoom similar like amazon when open on mobile view:

https://www.amazon.de/gp/aw/d/B01C37CRZS/?_encoding=UTF8&pd_rd_plhdr=t&aaxitk=d0cbebe4194d6edc5093cd9cda6b705d&hsa_cr_id=5069197050902&ref_=sbx_be_s_sparkle_scm_asin_0_img&pd_rd_w=SpWBU&pf_rd_p=93aef975-2fed-4353-91a2-d32b278d7c02&pd_rd_wg=rBmS8&pf_rd_r=5RZJMMX3CJ35EZN88GSC&pd_rd_r=2787af93-7ff4-4207-9d1a-187bd98b598f#immersive-view_1624784083156

**Comment by yifaneye** [comment]
Hi @a-tonchev ! Thank you for raising this issue up! 😄

I tried to duplicate this issue but cannot duplicate the behaviour that you had, as if I double-tap the image in full-screen mode it does not have a zoom-in effect. Would you like to tell me which browser and OS you used and their respective version, please? Thanks! 😀

**Comment by a-tonchev** [comment]
Hi @yifaneye can you try to zoom with 2 fingers? I have xiaomi pocophone, tried on mobile chrome.

**Comment by yifaneye** [comment]
Hi @a-tonchev , I did try to zoom with 2 fingers, as well as, double-tap. However, I can not replicate this issue. Thank you for providing me with this information! I will keep investigating.

**Comment by a-tonchev** [comment]
I made here video how it looks like:

https://vimeo.com/570653523

I think maybe a double tap or 2-finger zoom control would be better than the native behavior :)

**Comment by yifaneye** [comment]
Hi @a-tonchev , thanks for the video! I can see that you experienced this issue on your device. I will try to get it fixed.

**Comment by AnmolChhabra98** [comment]
Hi @yifaneye , @a-tonchev 
I have experienced the same issue. Is this fixed in this new version ?

**Comment by yifaneye** [comment]
Hi @AnmolChhabra98 ,
I can't replicate the issue. Would you like to give me more information?

**Comment by a-tonchev** [comment]
@yifaneye maybe you can use something similar like https://manuelstofer.github.io/pinchzoom/ 

But I am not sure if pinchzoom is the best choice

**Comment by yifaneye** [comment]
Thanks @a-tonchev. I will have a look!

**Comment by AnmolChhabra98** [comment]
@yifaneye Sorry for replying late. You can try these steps to reproduce:-

1) Zoom any image.
2) Zoom out from the image.
3) Try to move to the next image (& you are unable to move to the next image).

Or for more clarity, you can have a look at the video mentioned by @a-tonchev. 

I have experienced it on a mobile device and I am using user-managed slides.

**Comment by yifaneye** [comment]
@AnmolChhabra98 
Thanks for the information! I think I have found the issue. I will fix it in the next release!

**Comment by AnmolChhabra98** [comment]
@yifaneye That's great news 👍.

**Comment by yifaneye** [comment]
This issue is now fixed in v0.2.6.

**Comment by AnmolChhabra98** [comment]
Thanks, @yifaneye for this release but this isn't working as expected. I have tested it on my mobile device it is not moving to the next or previous slide after zoom.

**Comment by yifaneye** [comment]
Hi @AnmolChhabra98 ! Can this be a problem of the device? Would you like to debug for me, please?

**Comment by yifaneye** [comment]
Would you like to tell me what mobile device did you use? I will try it when I go to the electronics store. 😁

**Comment by a-tonchev** [comment]
@yifaneye you can open full screen mode and try to zoom in and out with 2 fingers. After that try to slide with the finger again (not with the arrow) I get this issue on all devices home :) Iphone 4, Pocophone f1, Samsung Galaxy Tab s7+

**Comment by AnmolChhabra98** [comment]
Hi @yifaneye, @a-tonchev, I have also tested on various mobile device but it is still the same. I have tested it on.
-> Realme X
-> Vivo v17, etc.

**Comment by AnmolChhabra98** [comment]
@yifaneye, Are you following the same steps as mentioned in just above comment by @a-tonchev ?

**Comment by yifaneye** [comment]
I have followed the steps mentioned. It works on my iPhone X. I will try it when I go to the electronics store.

**Comment by yifaneye** [comment]
Hi @AnmolChhabra98 @a-tonchev, I have fixed the issue using my friend's Samsung phone. Would you like to check it for me please?

**Comment by AnmolChhabra98** [comment]
Hi @yifaneye, Sorry for the late reply. I have tested the new release on my mobile device and it working perfectly, 
Thank you so much for fixing this😊.

**Comment by yifaneye** [comment]
Hi @AnmolChhabra98 ! No worries. Great news! It's my pleasure. 😄

**Comment by yifaneye** [comment]
Hi @a-tonchev ! No worries. Great news! It's my pleasure. 😁
