### ISSUE TITLE
Remove unused useEffect cleanup from example 4

### ISSUE THREAD

**Issue by guilhermefront** [yifaneye/react-gallery-carousel#45]
Hi, I was looking through some examples and saw this code:

https://github.com/yifaneye/react-gallery-carousel/blob/3adffccaf131e69eb084736aa24a0a2b47268fa8/example/src/components/Carousel4.js#L10

Doing this Is the same as not returning nothing and doesn't look like it helps to teach the lib, so I suggest to delete this line.

**Comment by yifaneye** [comment]
Hi @guilhermefront ! Thank you for raising this issue up! 😄

I can see that you are right! I will remove this unnecessary line.
