### ISSUE TITLE
Type issue on goToIndex

### ISSUE THREAD

**Issue by acewebsolutions** [yifaneye/react-gallery-carousel#50]
**Describe the bug**
When using the package with typescript and react there is an issue on the type of goToIndex. It's type does not support any parameters, when it should support (index:number)

**To Reproduce**
1. Install react-gallery-carousel and @types/react-gallery-carousel
2. Click on try to use ref.current.goToIndex(1)
3. See error (Expected 0 arguments, but got 1.) on the "1" paramenter of goToIndex

**Expected behavior**
No type error when using the index parameter on goToIndex;
If I'm not wrong, the CarouselRef type should be:

```
    type CarouselRef<T = unknown> = T & {
        ...
        goToIndex(index: number): void;
    };
```

**Comment by yifaneye** [comment]
Hi @acewebsolutions ! Thanks for raising this issue up! 😀

I can see the parameter is missing in `goToIndex ` function.

I will update the interface written by (@guilhermefront) and include it in the package.

**Comment by guilhermefront** [comment]
Sorry for the inconvenience @acewebsolutions @yifaneye 

@types/react-gallery-carousel got updated to 0.2.1 with the goToIndex parameter.

**Comment by yifaneye** [comment]
No worries @guilhermefront ! I am a little busy at the moment. Thank you for maintaining the type definition for react-gallery-carousel!
