### ISSUE TITLE
Invalid or unexpected token

### ISSUE THREAD

**Issue by jweb89** [yifaneye/react-gallery-carousel#51]
**Describe the bug**
SyntaxError: Invalid or unexpected token
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Josh\Documents\pcswaps\swap-react\node_modules\react-gallery-carousel\dist\index.js:5:40)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
C:\Users\Josh\Documents\pcswaps\swap-react\node_modules\react-gallery-carousel\dist\placeholder.jpg:1
�PNG

**To Reproduce**

I'm using Next.js in a monorepo with lerna but other than that I'm not exactly sure what's causing this issue. It looks like it might be trying to find placeholder.jpg(1) but I don't see why. I also cloned the repo and ran the next example and it seemed to work fine. I also tried not hoisting the this module and that didn't help. Kind of at a loss but I'm very excited to make use of this package. Been searching for some time for a good gallery that is performant rather than writing my own and it seems like you've done that.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/62513031/126919577-0ab4768d-342f-4b83-8fbb-5249409a480a.png)
![image](https://user-images.githubusercontent.com/62513031/126919710-c9bab3b5-5a4b-45e3-93f6-85c41cb291eb.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jweb89** [comment]
![image](https://user-images.githubusercontent.com/62513031/127072138-3833a7ff-8bea-46bf-8c77-611a534b2956.png)
![image](https://user-images.githubusercontent.com/62513031/127072193-fde6a139-45d9-46ed-b2d7-fe343db4d228.png)

Just to add some more information, this is the difference between my .next directory and the one outputted from your project. So maybe it's the difference between having it as a node_module vs having in it's own directory? I'm going to copy the dist into my own project to hopefully just get it working

**Comment by jweb89** [comment]
Yeah it does work with just copying the dist folder and importing it like a normal file so it must something about how next resolves images paths

**Comment by yifaneye** [comment]
Hi jweb89! Thank you for raising this issue up! 😃

I recall I got a similar issue before. At that time, I also wonder if it was Next.js that has compiled the files differently. I am glad to hear that you get it working again! Well done! 👏

**Comment by rokajova** [comment]
> Yeah it does work with just copying the dist folder and importing it like a normal file so it must something about how next resolves images paths

Did you get it to work? I'm still getting the same  `
SyntaxError: Invalid or unexpected token` as before.

**Comment by jweb89** [comment]
> > Yeah it does work with just copying the dist folder and importing it like a normal file so it must something about how next resolves images paths
> 
> Did you get it to work? I'm still getting the same ` SyntaxError: Invalid or unexpected token` as before.

Yeah you just can't use it as NPM package. I cloned this repo and just copied the dist folder to my project and imported it like a normal file. Are you using Next as well?

**Comment by nikoskleidis** [comment]
I also faced the same issue with NextJS 12. Hope it is fixed someday. I really liked this library!

**Comment by yifaneye** [comment]
I think I fixed the issue in v0.2.7. Please feel free to comment down below if this issue is still there after upgrading.

**Comment by yifaneye** [comment]
@jweb89 @rokajova @nikoskleidis Hi, I am wondering if you have tried the latest version?
