### ISSUE TITLE
Issues lazy loading images in gallery

### ISSUE THREAD

**Issue by jweb89** [yifaneye/react-gallery-carousel#52]
**Describe the bug**

Sometimes lazy loaded images don't load. From what I can see it doesn't get switched to a real url when swiping or clicking the url so when the image is actually on screen this causes the gallery to try to load the image from https://{path}/[object%20Object]

**To Reproduce**
Not exactly sure how to reproduce consistently, but here is an example 

Website has been updated to that issue is no longer present
This is our staging server. The login is dev/dev so you can see the behavior. I tried to do some debugging but couldn't find exactly what was causing the issue. The urls are definitely valid. This doesn't happen if lazy loading is disabled

**Expected behavior**
Should lazy load the image

**Screenshots**
![image](https://user-images.githubusercontent.com/62513031/127328292-061e58a2-c104-41b6-a7c0-9220d4b87b07.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows 10
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] iphone xr
 - OS: [e.g. iOS8.1] latest
 - Browser [e.g. stock browser, safari] safari

**Additional context**

This does happen on my iphone as well. See specs above.

**Comment by yifaneye** [comment]
Hi @jweb89 ! Thank you for raising this issue up! 😃

May I know which version of the package are you using?

**Comment by jweb89** [comment]
Using the latest version which was done from the cloned repo since I had the issue using it as node module with next js. I was also able to sometimes get the next js example repo you provided to produce the issue but it was never consistent. From what I can see the image src isn't getting updated before the image actually tried to be fetched and then it just defaults back to the placeholder/error image

**Comment by yifaneye** [comment]
I see. I had some custom implementation of the lazy loading behaviour in order to support all browsers. I will continue to investigate it.

**Comment by yifaneye** [comment]
Sorry, I still have not figured out the cause yet.

**Comment by yifaneye** [comment]
I think I fixed the issue in v0.2.7 while fixing issue #51. Please feel free to comment down below if this issue is still there after upgrading.

**Comment by yifaneye** [comment]
@jweb89 @rhayart I am wondering if you have tried the latest version?

**Comment by rhayart** [comment]
Hi ! I just test the v0.2.7 and it seems to be ok now. Good job, thanks !

**Comment by yifaneye** [comment]
@rhayart Awesome! My pleasure!
