### ISSUE TITLE
Allow thumbnails to be at the side

### ISSUE THREAD

**Issue by KMouratidis** [yifaneye/react-gallery-carousel#55]
**Is your feature request related to a problem? Please describe.**
I'm trying to move the thumbnails from the bottom to the right, like the image below which I did by modifying the CSS, but the problem is that mouse events (`useMouse`/`useMouseDrag` ?) only work on the X direction.

**Describe the solution you'd like**
Allow a new prop (`orientation`?) to be passed to mouse event handers (possibly separate for thumbnails and images).

**Describe alternatives you've considered**
None, not sure what I could try.

**Additional context**

What I want to do:
![image](https://user-images.githubusercontent.com/26832680/132092602-2d192551-47f5-4913-90bf-aad35c97bc1a.png)

CSS, roughly:
```
<thumbnail> ul {
  display: flex;
  flex-direction: column;
}

<thumbnail> ul li {
  min-width: 100%;
  min-height: 10%;
}
```

**Comment by yifaneye** [comment]
Hi @KMouratidis ! Thanks for raising this issue up! 😀

I agree that you can override the CSS but you can not do much on the event listeners. So you would like to have the thumbnails be placed vertically and be scrolled vertically right?

**Comment by KMouratidis** [comment]
Yes, that's what I wanted to do. I did try messing with the X/Ys a little but couldn't get it to work (being a JS newbie). If you don't have the time, I don't mind giving it another try later this month.

**Comment by yifaneye** [comment]
@KMouratidis Thanks for the clarification. I am happy to have a look at this month.
