### ISSUE TITLE
Carousel Button Titles

### ISSUE THREAD

**Issue by Aldemylla** [yifaneye/react-gallery-carousel#60]
**Is your feature request related to a problem? Please describe.**
When hovering over the circular button, I have the title "Go" or "Stay".

**Describe the solution you'd like**
I would like to be able to change/translate these titles.

**Describe alternatives you've considered**
Or just be able to get them out of there.

**Additional context**
![image](https://user-images.githubusercontent.com/69015179/141479475-176d46f1-130e-46ed-b080-0d7095a4e8f5.png)

**Comment by yifaneye** [comment]
@Aldemylla 
Thanks for raising this issue up! I will remove the "labels" in the next release!

**Comment by yifaneye** [comment]
This issue is now fixed in v0.2.6.
