### ISSUE TITLE
Typo: minIcon Typescript type is not accepted by Carousel Component

### ISSUE THREAD

**Issue by mohanzeal** [yifaneye/react-gallery-carousel#69]
**Describe the bug**
minIcon is the actual prop that Carousel component accepts as per the api(https://github.com/yifaneye/react-gallery-carousel#props) but **@types/react-gallery-carousel** has typo  miniIcon

Please check the screenshots below

**Issue:**
I am using this in a nextjs project everything works but nextjs is not building the project because of the type error.

**Screens
<img width="1220" alt="Screenshot 2022-02-06 at 4 29 28 PM" src="https://user-images.githubusercontent.com/5113135/152677807-27601a1a-c849-44c4-b6c4-26b3c4fd90cf.png">

Check last but one prop in the above image

next js build issue due to the typo.
<img width="1220" alt="Screenshot 2022-02-06 at 4 27 10 PM" src="https://user-images.githubusercontent.com/5113135/152677814-32508a29-cd7c-412b-b6e9-82fd89bf2640.png">

**Comment by guilhermefront** [comment]
> Hi @mohanzeal ! Thank you for raising this issue up. Hi @guilhermefront ! Would you like to fix it? Please let me know if you don't have time.

Yes, did a PR for fixing this and adding types for other props like thumbnails
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58748

@mohanzeal sorry for the late fix, I hadn't received a notification until @yifaneye mentioned me

**Comment by mohanzeal** [comment]
no issues @guilhermefront, and thanks to everyone who build this great carousel component.. It helped me a lot.

**Comment by guilhermefront** [comment]
A new version with the fix was published (0.2.2), updating should solve this problem

`npm update @types/react-gallery-carousel`

**Comment by mohanzeal** [comment]
Hey @guilhermefront, thanks for the fix. 

I can confirm the issue is resolved.
