### ISSUE TITLE
npm install doesnt work on react-gallery-carousel/example/

### ISSUE THREAD

**Issue by damdafayton** [yifaneye/react-gallery-carousel#72]
**Describe the bug**
I managed to install dependencies but I still get this error:
```
./src/components/Carousel1.js
Cannot find file: 'TwoWayMap.js' does not match the corresponding name on disk: '.\src\utils\twoWayMap.js'.
``` 
And there is no such file under `\utils\`

**To Reproduce**
```
npm install
npm start
```

**Fix**
`import TwoWayMap from '../utils/TwoWayMap';`
needs to be
`import TwoWayMap from '../utils/twoWayMap';`

**Comment by yifaneye** [comment]
Hi @damdafayton ! Thank you for raising this issue up.

I can't reproduce your bug. But I see the difference in the naming. I will fix it.

**Comment by yifaneye** [comment]
Hi @damdafayton ! Sorry for the late reply!

![SS 2022-10-14 at 22 54 53](https://user-images.githubusercontent.com/49315663/195840943-fcb2e23c-e824-406d-9ba7-7c45106dc84a.jpg)
![SS 2022-10-14 at 22 45 44](https://user-images.githubusercontent.com/49315663/195839726-b41b4002-531b-4256-a445-5f513c92d742.jpg)
The case in the name of the file is correct in the repo on my Mac. However, I can see that it is wrong in this GitHub repo and in my newly-cloned repo.
![SS 2022-10-14 at 22 52 06](https://user-images.githubusercontent.com/49315663/195840737-f17f5603-994f-4662-9cbf-4f3cae57b9b7.jpg)
![SS 2022-10-14 at 22 52 28](https://user-images.githubusercontent.com/49315663/195840740-fe5c1d5f-bcff-441e-96a8-09ce270eb68f.jpg)

I will fix it this weekend.

**Comment by yifaneye** [comment]
Hi @damdafayton !

In v0.3.0, I corrected the case in the name of the file. 😁
