### ISSUE TITLE
Add option for scroll bar for thumbnails 

### ISSUE THREAD

**Issue by jingdid** [yifaneye/react-gallery-carousel#75]
**Is your feature request related to a problem? Please describe.**
I'm using the carousel in a context where there are likely to be hundreds of thumbnails. In this case the user will likely want to use the thumbnails to navigate to the right slide, but the user is likely to only have access to a vertical scroll wheel on a mouse, making looking through all the thumbnails difficult.

**Describe the solution you'd like**
It would be nice if there could be a prop enabling a scrollbar to show up allowing the user to scroll through the thumbnails.

**Describe alternatives you've considered**
I tried overriding the css in the component to add a scrollbar to the thumbnails container, but because I wasn't accessing the container directly, the effect ended up being that I stole vertical space from the thumbnails, making them so small that they were unusable for navigation, defeating the purpose. If this feature were native, then an option to enable the scrollbar could perhaps instead borrow the needed space from the image panel, where those pixels are less likely to make such a dramatic difference. I also looked into whether there is a way to convert vertical scroll wheel inputs into horizontal scrolling, but the hacks I found didn't seem to work without direct access to the component.

**Additional context**
Thank you :)

**Comment by yifaneye** [comment]
Hi @jingdid Thanks for raising this issue up! I will investigate it!

**Comment by yifaneye** [comment]
Hi @jingdid ! Your request is valid and reasonable. Sorry for the late reply!

For overriding the CSS to add a scrollbar, you can unset this property.
![SS 2022-10-14 at 22 23 15](https://user-images.githubusercontent.com/49315663/195835588-56aa349e-a906-4389-af3e-7f9e15248bc8.jpg)

For compensating the vertical space from the thumbnails, you can customize the `thumbnailHeight` prop.
Please see [the docs](https://github.com/yifaneye/react-gallery-carousel#props).

For converting vertical scroll wheel inputs into horizontal scrolling, I think it is quite hard.
